In [17]:
import pandas as pd
import numpy as np 
import itertools
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [18]:
df=pd.read_csv("news.csv", index_col=None)

In [19]:
df

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL


In [20]:
dataset=df.drop("Unnamed: 0", axis=1)

In [21]:
dataset

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL


In [22]:
y=dataset["label"]

In [23]:
X_train,X_test,Y_train,Y_test=train_test_split(dataset['text'],y,test_size=0.33,random_state=53)

In [24]:
tfidf=TfidfVectorizer(stop_words='english')
X_train_tfidf=tfidf.fit_transform(X_train)
X_test_tfidf=tfidf.transform(X_test)
print(X_train_tfidf)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1119820 stored elements and shape (4244, 56922)>
  Coords	Values
  (1, 42470)	0.07711040274149526
  (1, 12105)	0.15008066461476866
  (1, 54177)	0.13782629144711137
  (1, 50628)	0.061296988343109586
  (1, 15924)	0.3479045460649079
  (1, 44520)	0.4973826512693341
  (1, 51896)	0.11596517664605868
  (1, 35783)	0.30902690818827977
  (1, 35256)	0.12628385718450857
  (1, 21881)	0.21271688045815978
  (1, 42534)	0.06081715886809217
  (1, 8399)	0.08729542880625335
  (1, 29531)	0.1454406205718245
  (1, 15927)	0.4973826512693341
  (1, 25686)	0.13550453594288983
  (1, 49203)	0.1672740861784377
  (1, 16814)	0.10404977746548139
  (1, 36087)	0.12648679854389897
  (1, 21568)	0.1007920919566398
  (1, 25684)	0.1030420922189754
  (1, 38823)	0.06048803110658644
  (1, 47506)	0.14539060877460044
  (1, 36831)	0.10772488937433067
  (2, 16972)	0.1606296088662543
  (2, 762)	0.48803966069171073
  :	:
  (4243, 41435)	0.02969665315895183
  (4243, 53607)	

In [25]:
len(tfidf.get_feature_names_out())

56922

In [26]:
print(X_train_tfidf.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [31]:
# model using multinomial
clf=MultinomialNB()
clf.fit(X_train_tfidf,Y_train)
pred=clf.predict(X_test_tfidf)
score=metrics.accuracy_score(Y_test,pred)
print("accuracy: %0.3f"%score)
cm=metrics.confusion_matrix(Y_test,pred,labels=["FAKE","REAL"])

accuracy: 0.857


In [32]:
cm

array([[ 739,  269],
       [  31, 1052]])

In [35]:
from sklearn.metrics import classification_report
report=classification_report(Y_test,pred)
print(report)

              precision    recall  f1-score   support

        FAKE       0.96      0.73      0.83      1008
        REAL       0.80      0.97      0.88      1083

    accuracy                           0.86      2091
   macro avg       0.88      0.85      0.85      2091
weighted avg       0.88      0.86      0.85      2091



In [36]:
# Prediction process 
dataset["text"][0]

'Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. \nIn the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. \nThe word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. \nBut that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. \nThe FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. \nThe FBI’s leadership is being warned that the entir

In [37]:
# text is converted to vector before the testing prediction
tfidf=TfidfVectorizer(stop_words="english")
X_train_tfidf=tfidf.fit_transform(X_train)
X_test_tfidf=tfidf.transform(X_test)

In [38]:
X_train_tfidf[[0]]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 0 stored elements and shape (1, 56922)>

In [39]:
print(X_test_tfidf)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 533697 stored elements and shape (2091, 56922)>
  Coords	Values
  (0, 2385)	0.04673510209222487
  (0, 3184)	0.06954723147734826
  (0, 4067)	0.05666340098468139
  (0, 4919)	0.04824871588215696
  (0, 5460)	0.15762013389393498
  (0, 7383)	0.058563792627012654
  (0, 7422)	0.06994531311121911
  (0, 7464)	0.09887000461121552
  (0, 10525)	0.03238028580548933
  (0, 10673)	0.1000711492265641
  (0, 10984)	0.07780444275234664
  (0, 10985)	0.1612727978010528
  (0, 12457)	0.06547534804793215
  (0, 12601)	0.07881006694696749
  (0, 13343)	0.09568195059113496
  (0, 14163)	0.038181501713474654
  (0, 14446)	0.130821972163052
  (0, 14867)	0.034681321392149966
  (0, 15085)	0.0971987263420166
  (0, 15285)	0.09568195059113496
  (0, 15812)	0.04537185367441499
  (0, 15870)	0.036221638456254444
  (0, 15942)	0.25431588191329985
  (0, 16027)	0.5086317638265997
  (0, 16580)	0.04730867818016224
  :	:
  (2090, 52119)	0.0381402419774901
  (2090, 52134)	0.

In [40]:
# wanted to test the output for X_test sample in index 6331
X_test[[6331]]

6331    The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
Name: text, dtype: object

In [42]:
X_test_tfidf.shape

(2091, 56922)

In [43]:
6331 in X_test.index

True

In [44]:
# finding the exact row position of X_test sample
pos=X_test.index.get_loc(6331)
print(pos)

737


In [45]:
clf.predict(X_test_tfidf[737:738])

array(['FAKE'], dtype='<U4')